#!/usr/bin/env python3
"""
Download classification source files into data/ (where publicly available).

Downloads automatically:
  - Uniclass 2015 Pr, Ss, EF via buildig/uniclass-2015 (GitHub mirror of NBS — NOT the
    live thenbs.com feed; verify against https://www.thenbs.com/uniclass before citing codes)
  - NL-SfB tables 0-4 (BIM Loket / STABU blob) -> nlsfb_table1.xlsx, nlsfb_table3.xlsx

ETIM 9 Excel (public release zip from ETIM International).

Run: python scripts/download_source_data.py
"""

from __future__ import annotations

import shutil
import sys
import urllib.request
import zipfile
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"

# Mirror of NBS Uniclass 2015 (Jan 2022 snapshot on GitHub). If this repo goes stale,
# download current tables from https://www.thenbs.com/uniclass/download and replace data/*.xlsx.
UNICLASS_CSV_URLS = {
    "uniclass_pr.csv": "https://raw.githubusercontent.com/buildig/uniclass-2015/master/uniclass2015/Uniclass2015_Pr.csv",
    "uniclass_ss.csv": "https://raw.githubusercontent.com/buildig/uniclass-2015/master/uniclass2015/Uniclass2015_Ss.csv",
    "uniclass_ef.csv": "https://raw.githubusercontent.com/buildig/uniclass-2015/master/uniclass2015/Uniclass2015_EF.csv",
}

NLSFB_COMBINED_URL = (
    "https://stprodeuwmystabu002stor.blob.core.windows.net/overig/"
    "NL-SfB_Tabel_0-4_Update-V202112.xlsx"
)

ETIM_ZIP_URL = (
    "https://www.etim-international.com/wp-content/uploads/2022/12/"
    "ETIM-9.0-ALL-SECTORS-EXCEL-METRIC-EI-2022-12-05.zip"
)
ETIM_XLSX_IN_ZIP = "ETIM-9.0-ALL-SECTORS-EXCEL-METRIC-EI-2022-12-05.xlsx"


def _download(url: str, dest: Path) -> None:
    print(f"Downloading {dest.name} ...")
    urllib.request.urlretrieve(url, dest)


def download_uniclass() -> None:
    for filename, url in UNICLASS_CSV_URLS.items():
        xlsx_path = DATA / filename.replace(".csv", ".xlsx")
        if xlsx_path.exists():
            print(f"Skipping {xlsx_path.name} (exists)")
            continue
        csv_path = DATA / filename
        _download(url, csv_path)
        df = pd.read_csv(csv_path)
        df.to_excel(xlsx_path, index=False)
        print(f"  -> {xlsx_path.name} ({len(df)} rows)")


def download_nlsfb() -> None:
    combined = DATA / "nlsfb_combined.xlsx"
    if not combined.exists():
        _download(NLSFB_COMBINED_URL, combined)

    for sheet, out_name in [
        ("NL-SfB_Tabel 1", "nlsfb_table1.xlsx"),
        ("NL-SfB_Tabel 3", "nlsfb_table3.xlsx"),
    ]:
        out = DATA / out_name
        if out.exists():
            print(f"Skipping {out.name} (exists)")
            continue
        df = pd.read_excel(combined, sheet_name=sheet)
        df.to_excel(out, index=False)
        print(f"  -> {out.name} ({len(df)} rows from sheet '{sheet}')")

    legacy = DATA / "nlsfb.xlsx"
    if not legacy.exists():
        shutil.copy(combined, legacy)
        print(f"  -> {legacy.name} (copy of combined)")


def download_etim() -> None:
    dest = DATA / "etim.xlsx"
    if dest.exists():
        print(f"Skipping etim.xlsx (already exists, {dest.stat().st_size // 1024} KB)")
        return

    zip_path = DATA / "etim9.zip"
    if not zip_path.exists():
        _download(ETIM_ZIP_URL, zip_path)

    extract_dir = DATA / "etim_extract"
    extract_dir.mkdir(exist_ok=True)
    src = extract_dir / ETIM_XLSX_IN_ZIP
    if not src.exists():
        with zipfile.ZipFile(zip_path) as zf:
            zf.extractall(extract_dir)

    shutil.copy(src, dest)
    print(f"  -> {dest.name} ({dest.stat().st_size // 1024} KB)")


def write_status() -> None:
    status = DATA / "DOWNLOAD_STATUS.md"
    lines = [
        "# Source data download status",
        "",
        "Generated by `python scripts/download_source_data.py`.",
        "",
        "| File | Status | Source |",
        "|------|--------|--------|",
    ]
    files = [
        ("uniclass_pr.xlsx", "Uniclass Pr", "buildig/uniclass-2015 mirror — verify at thenbs.com/uniclass"),
        ("uniclass_ss.xlsx", "Uniclass Ss", "buildig/uniclass-2015 mirror"),
        ("uniclass_ef.xlsx", "Uniclass EF", "buildig/uniclass-2015 mirror"),
        ("nlsfb_table1.xlsx", "NL-SfB Table 1", "BIM Loket / STABU blob"),
        ("nlsfb_table3.xlsx", "NL-SfB Table 3", "BIM Loket / STABU blob"),
        ("etim.xlsx", "ETIM 9", "ETIM International release zip"),
    ]
    for fname, label, source in files:
        path = DATA / fname
        st = "OK" if path.exists() else ("**Missing — manual**" if "etim" in fname else "Missing")
        lines.append(f"| `{fname}` | {st} | {source} |")
    lines.extend(
        [
            "",
            "## Verify",
            "",
            "```bash",
            "python -m src.loader --table pr",
            "python -m src.loader --table nlsfb1",
            "python -m src.loader --table nlsfb3",
            "python scripts/suggest_etim_matches.py  # after etim.xlsx present",
            "```",
            "",
        ]
    )
    status.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {status}")


def main() -> int:
    DATA.mkdir(parents=True, exist_ok=True)
    try:
        download_uniclass()
        download_nlsfb()
        download_etim()
    except Exception as exc:
        print(f"Download failed: {exc}", file=sys.stderr)
        return 1
    write_status()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
